Traceback (most recent call last):=====                         ] 1056.00 MB / 2045.15 MB (0.63 MB/s)
  File "bin/gletscher", line 85, in <module>
    args.fn(args)
  File "/home/pmoor/gletschter/gletscher/commands/backup.py", line 76, in backup_command
    config, index, data_file, data_file_slot)
  File "/home/pmoor/gletschter/gletscher/commands/backup.py", line 124, in _finalize_data_file
    "tree-hash": hex.b2h(tree_hash),
  File "/home/pmoor/gletschter/gletscher/aws.py", line 377, in upload_file
    connection, pending_upload, data, hex.b2h(tree_hash), start)
  File "/home/pmoor/gletschter/gletscher/aws.py", line 187, in _uploadPart
    connection.request("PUT", path, body=payload, headers=headers)
  File "/usr/lib64/python3.2/http/client.py", line 967, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.2/http/client.py", line 1005, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.2/http/client.py", line 963, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.2/http/client.py", line 808, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.2/http/client.py", line 777, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.2/ssl.py", line 371, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python3.2/ssl.py", line 338, in send
    v = self._sslobj.write(data)
socket.error: [Errno 110] Connection timed out


Traceback (most recent call last):
  File "bin/gletscher", line 85, in <module>
    args.fn(args)
  File "/home/pmoor/gletschter/gletscher/commands/backup.py", line 76, in backup_command
    config, index, data_file, data_file_slot)
  File "/home/pmoor/gletschter/gletscher/commands/backup.py", line 124, in _finalize_data_file
    "tree-hash": hex.b2h(tree_hash),
  File "/home/pmoor/gletschter/gletscher/aws.py", line 372, in upload_file
    connection, pending_upload, data, hex.b2h(tree_hash), start)
  File "/home/pmoor/gletschter/gletscher/aws.py", line 186, in _uploadPart
    connection.request("PUT", path, body=payload, headers=headers)
  File "/usr/lib64/python3.2/http/client.py", line 967, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.2/http/client.py", line 1005, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.2/http/client.py", line 963, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.2/http/client.py", line 808, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.2/http/client.py", line 777, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.2/ssl.py", line 371, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python3.2/ssl.py", line 338, in send
    v = self._sslobj.write(data)
socket.error: [Errno 104] Connection reset by peer


Traceback (most recent call last):==========================    ] 1920.00 MB / 2046.47 MB (0.63 MB/s)
  File "bin/gletscher", line 85, in <module>
    args.fn(args)
  File "/home/pmoor/gletschter/gletscher/commands/backup.py", line 76, in backup_command
    config, index, data_file, data_file_slot)
  File "/home/pmoor/gletschter/gletscher/commands/backup.py", line 124, in _finalize_data_file
    "tree-hash": hex.b2h(tree_hash),
  File "/home/pmoor/gletschter/gletscher/aws.py", line 377, in upload_file
    connection, pending_upload, data, hex.b2h(tree_hash), start)
  File "/home/pmoor/gletschter/gletscher/aws.py", line 187, in _uploadPart
    connection.request("PUT", path, body=payload, headers=headers)
  File "/usr/lib64/python3.2/http/client.py", line 967, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.2/http/client.py", line 1005, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.2/http/client.py", line 963, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.2/http/client.py", line 808, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.2/http/client.py", line 777, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.2/ssl.py", line 371, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python3.2/ssl.py", line 338, in send
    v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe
